name: "invalid-issue-closer"
description: "Close an issue if it meets some requirements"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true

  labels:
    description: "A comma-separated list of labels to apply"

  comment:
    description: "A GitHub Flavored Markdown string to comment on the invalid issue"

  # Possible conditions
  title-contains:
    description: "String to search for in issue title"
  body-contains:
    description: "String to search for in issue body"
runs:
  using: "node12"
  main: "dist/index.js"
