# test action works running from the graph
on:
  issues:
    types: [opened, reopened]

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "invalid :no_entry_sign:"
          comment: "This was a successful test of the issue closing system."
          title-contains: "<PUT TITLE HERE>"
          body-contains: "<!-- Tips: where applicable, specify browser name, browser version, and mobile operating system version -->\r\n\r\n#### What information was incorrect, unhelpful, or incomplete?\r\n\r\n#### What did you expect to see?\r\n\r\n#### Did you test this? If so, how?\r\n\r\n"
